# docker-compose.dev.yml (for development)
services:
  postgres:
    image: postgres:15-alpine
    container_name: mentorship-postgres-dev
    environment:
      POSTGRES_DB: mentorship_portal_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mentorship-network

  redis:
    image: redis:7-alpine
    container_name: mentorship-redis-dev
    ports:
      - "6379:6379"
    networks:
      - mentorship-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: mentorship-backend-dev
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mentorship_portal_dev
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: dev-secret-key-change-in-production
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - ./backend/uploads:/app/uploads
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    networks:
      - mentorship-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: mentorship-frontend-dev
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mentorship-network

volumes:
  postgres_dev_data:
  backend_node_modules:
  frontend_node_modules:

networks:
  mentorship-network:
    driver: bridge